ALTER TABLE users
  ADD COLUMN created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
  ADD COLUMN updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';

ALTER TABLE user_profile
  ADD COLUMN created_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM',
  ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN updated_by VARCHAR(100) NOT NULL DEFAULT 'SYSTEM';
